### ISSUE TITLE
License please?

### ISSUE THREAD

**Issue by nickvargish** [nikunjness/mongo-ambari#1]
Hi, this is really cool, it's something I've been anticipating doing for a project of mine.

Is there any chance you could add a license file?  I don't like using others' code without some idea of their intentions.

Personally, I've used the BSD license for some of my own stuff. I've also released pure public domain works, though I'm not sure what the formal license for that looks like.

Thanks!

**Comment by nikunjness** [comment]
Hi Nick,

I will definitely include license file. Thanks for suggestion. Let me know
if you find any bug or need any improvement.

Cheers,
Nikunj

**Comment by nickvargish** [comment]
Haha, perfect. Thanks!
