### ISSUE TITLE
mongod.conf.j2 template doesn't expand values

### ISSUE THREAD

**Issue by nickvargish** [nikunjness/mongo-ambari#2]
In the mongod.conf.j2 template, I suggest changing:
# port=27017

to
# port={{tcp_port}}

dbpath=/var/lib/mongo
to
dbpath={{db_path}}
# bind_ip=127.0.0.1

to
# bind_ip={{bind_ip}}

Maybe uncomment the commented-out values, since they are set to default by the configurator?

**Comment by vutny** [comment]
I have got this issue fixed in PR #4 along with support for MongoDB 3.2 installation.
